### ISSUE TITLE
Add to bioconda repository

### ISSUE THREAD

**Issue by tdido** [csb-toolbox/CSB#2]
Hey guys.

Back in the day I got the package into Debian, but honestly I'm now almost exclusively using conda for my environments. I saw that there's a package by @ivan-kalev in his private anaconda repo, and some others by other people/projects, but it's not yet in bioconda I think? I'd be happy to get it there if there's interest.

**Comment by ivan-kalev** [comment]
Having CSB in bioconda makes a lot of sense. It would be great if you can get this done!

Building a conda recipe for csb should be very simple. Also now that we are on GitHub and we have a working Travis CI build, feel free to modify the Travis build plan if you think Travis can help with building conda packages.

**Comment by tdido** [comment]
bioconda recipe merged into master. Package should be available in the repo soon.

**Comment by speleo3** [comment]
questions regarding the new bioconda recipe:

- why are numpy, scipy and matplotlib build-time dependencies?
- why is libgcc a runtime dependency (csb is a pure Python package)?

**Comment by tdido** [comment]
The libgcc dependency is required because of the way Travis is set up, apparently. It's something specific to the bioconda build process.

The other dependencies may actually not be needed, I don't think I tried building without them. I'll try it for the next release.

**Comment by speleo3** [comment]
If libgcc is for the test run on Travis, then I'd suggest to add it as a test dependency instead

```
test:
  requires:
    - libgcc  # [linux]
```

**Comment by tdido** [comment]
I have the feeling I did try that and it didn't work, but I'll give it a shot as well for the next release.
